version: "3.9"
services:
  app:
    container_name: ts-fastify-docker
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT=3000
    depends_on:
      db:
        # dbコンテナの起動が起動し、healthcheckが通ったらappコンテナが起動する
        condition: service_healthy
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - "3000"
      - "9229"
    # env_file:
    #   - .env
    volumes:
      # プロジェクト内のnode_modulesを除いたすべてのファイルとディレクトリの変更をコンテナ側にマウントする
      # 1. docker側のコンテナでホスト側のファイルシステムの変更を検知できるようにマウントする
      - ./:/usr/src/app
      # 2. ホスト側のnode-modulesがコンテナ側にマウントされることを防止する
      - exclude:/usr/src/app/node_modules/
    command: >-
      bash -c "npx prisma db push --force-reset --schema ./prisma/schema.prisma &&
      npm run run:dev"

  db:
    image: mysql:5.7
    platform: linux/x86_64 # M1 Macだとこれ設定しないとちゃんと動かない
    container_name: mysqldb
    tty: true
    stdin_open: true
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: mydb
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password # 任意のPWを設定する
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
      # MYSQL_ROOT_PASSWORDは今回設定していないが必要に応じて設定する。
      # .env の接続情報も編集すること
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      # mysqlが使用可能かどうかをチェックする
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

volumes:
  exclude:
