FROM node:18

ARG PORT

WORKDIR /usr/src/app

COPY package.json .

RUN npm install && npm cache clean --force

COPY . .

EXPOSE ${PORT}

ENV ADDRESS=0.0.0.0 PORT=${PORT}

CMD ["npm", "run", "run:dev"]
